# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{oauth-wrap}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Marcel Jackwerth"]
  s.date = %q{2010-01-21}
  s.description = %q{TODO: longer description of your gem}
  s.email = %q{marcel@northdocks.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/oauth_wrap.rb",
     "lib/oauth_wrap/consumer/exceptions.rb",
     "lib/oauth_wrap/consumer/web_app.rb",
     "spec/fake_server.rb",
     "spec/fixtures.rb",
     "spec/monkey_patches.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/web_app_continue_spec.rb",
     "spec/web_app_refresh_spec.rb",
     "spec/web_app_request_spec.rb"
  ]
  s.homepage = %q{http://github.com/sirlantis/oauth-wrap-ruby}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{TODO: one-line summary of your gem}
  s.test_files = [
    "spec/fake_server.rb",
     "spec/fixtures.rb",
     "spec/monkey_patches.rb",
     "spec/spec_helper.rb",
     "spec/web_app_continue_spec.rb",
     "spec/web_app_refresh_spec.rb",
     "spec/web_app_request_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<httparty>, [">= 0"])
      s.add_development_dependency(%q<mocha>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<webmock>, [">= 0"])
    else
      s.add_dependency(%q<httparty>, [">= 0"])
      s.add_dependency(%q<mocha>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<webmock>, [">= 0"])
    end
  else
    s.add_dependency(%q<httparty>, [">= 0"])
    s.add_dependency(%q<mocha>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<webmock>, [">= 0"])
  end
end

